INSERT INTO `answer` (`chinese`, `english`) VALUES ('', 'GO');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('HOLD不住', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('emmm…，奇怪的问题', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一个人安安静静待一会儿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一个人安安静静，待一会儿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一个人的朝圣', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一个人的细水长流', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一个强有力的承诺会取得更好的结果', 'A Strong Commitment Will Achieve Good Results');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一个强有力的承诺会换回更好的结果', 'A Strong Commitment Returns Better Results');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一个正在到来的晴天', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一切从头开始', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一切皆有可能', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一切都是徒劳', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一切顺其自然', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一千年以后', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一场完美的悲剧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一场羁绊', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一定会有好结果的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一年以后，无关紧要', 'A Year From Now It Won''t Matter');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一年后就不那么重要了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一成不变', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一无所有', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一条没有鲜花的道路', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一步之遥', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一直在找什么', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一直是个，幸运的人呢', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一笑了之', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一笑置之', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('一笑而过', 'Laugh About It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('万一错过，就没这个机会了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('万丈高楼平地起，成功还得靠自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('三思而后行', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('上天关上一扇门，必将开启新的窗', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('上帝为你关一扇门，必定会为你打开一扇窗', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('下一个天亮', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('下一页才是你的人生答案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('下一页，才是你的人生答案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('下次旅途中，你会找到答案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('下这一注稳赢', 'Bet On It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不会作就不会死', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不会后悔的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不会失望的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不作死就不会死', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不值得', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不值得冒险', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不值得斗争', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不可预测', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不合适', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不如忘掉这个问题', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不如赌一把', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不妥协', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不妨一试', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不宜在这个时候', 'Unfavorable At This Time');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不幸的是极有可能的', 'Mishaps Are Highly Probable');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不必为你无法控制的事情而担心', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不必在意', 'Don''t Be Concerned');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不必耿耿于怀', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不必要的退让', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不放赌一把', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不明智', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不是', 'No');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不是所有的事儿，努力都有用', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不然呢？', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不甘心就，努力争取吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不甘心的话，就努力争取吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不用伪装到面目全非', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不用怀疑了', 'Don''t Doubt It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不用担心', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不知所措', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不确定的因素有点多', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不管你做什么，结果将持久', 'Whatever You Do The Results Will Be Lasting');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不管是什么', 'No Matter What');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不能永远一成不变', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要一成不变', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要做出任何决定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要做得太过分', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要做得过火了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要做梦了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要刻意压抑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要刻意隐藏', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要去忘记', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要妥协', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要害怕', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要忘记', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要忘记微笑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要忘记有乐趣', 'Don''t Forget To Have Fun');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要忧虑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要忽视显而易见的', 'Don''t Ignore The Obvious');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要忽视自己的力量', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要怕', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要把所有表情都写在脸上', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要把所有表情，都写在脸上', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要抱期望', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要担心', 'Don''t Be Concerned');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要指望它', 'Don''t Bet On It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要浪费你的时间了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要浪费时间', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要浪费精力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要犹豫', 'Don''t Hesitate');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要看轻别人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要等了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要等待', 'Don''t Wait');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要纠结了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要给人添麻烦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要给别人添麻烦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要胡来', 'Don''t Overdo It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要自作多情', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要被心情所影响', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要被情绪左右', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要被情绪所控制', 'Don''t Get Caught Up In Your Emotions');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要让别人知道', 'Keep It To Yourself');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要让压力导致你反应过激', 'Don''T Be Pressured Into A Acting Too Quickly');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要赌', 'Don''t Bet On It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要轻易去相信', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要过分', 'Don''t Overdo It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要过火', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要迫于压力太快', 'Don''t Be Pressured Into Acting Too Quickly');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要迫于压力而改变初衷', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要陷入你的感情', 'Don''t Get Caught Up In Your Emotions');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要陷得太深', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要隐藏起来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不要饿着肚子，做重要决定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不赌', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不雅忽略身边的人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不需要', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('不，除非你是孤独的', 'Not If You''re Alone');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('与你无关', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('与其奋力挣扎，不如闭眼享受', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('与另一种情况有潜在的联系', 'There Is A Substantial Link To Another Situation');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('专注一点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('专注于你的家庭生活', 'Focus On Your Home Life');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('且行且思', 'watch your step as you go');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('世上无难事，只要肯放弃', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('世事难如愿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为了做最好的决定，冷静', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为了确保最好的结果，保持冷静', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为了确保能作出最佳决策，需要保持冷静', 'To Ensure The Best Decision, Be Calm');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为了走的更远你必须弥补这个缺点', 'You''ll Have To Make It Up As You Go');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为什么不', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为什么不做一个列表', 'Make A List Of Why Not');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为什么不列出原因', 'Make A List Of Why Not');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为什么不呢', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为做最好的决定，保持冷静', 'To Ensure The Best Decision, Be Calm');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('为突发事件做好准备', 'Prepare For The Unexpected');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('主动一点，人生会大不相同', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('主动点，可能会有好事发生', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('也许', 'Maybe');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('也许会有好转', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('也许会迟到', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('也许有惊喜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('也许有更好的解决方案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('也许，当你老了', 'Perhaps, When You''re Older');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('了不起', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('事情开始变得有趣了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('事情很快，会有变化的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('亏本买卖', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('享受全心全意的付出', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('享受这种经历', 'Enjoy The Experience');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('人生不如意，十有之十', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('人生总是如此痛苦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('今朝有酒，今朝醉', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('从来没有', 'Never');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('从现在开始 一年也没有关系', 'A Year From Now It Won''t Matter');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('仔细想想再说', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('仔细倾听；然后你就会知道', 'Listen More Carefully; Then You Will Know');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('令人期待的事情马上要发生', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('令人震惊的事件可能发生的', 'Startling Events May Occur As A Result');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('以丧治丧，以甜还甜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('以后再说', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('以后处理', 'Deal With It Later');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('仿佛它以成真', 'Act A Though It Is Already Real');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('仿佛它已成真', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('休息一下就好了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('休息，休息一会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('众所周知', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('优秀', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会付出代价', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会后悔的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会失去自我', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会很不顺利', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会很棒的', 'It''s Gonna Be Great');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会很顺利', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会感到庆幸', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会是完美的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会是甜的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会有一个风光明媚的未来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会有一些困难', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会有人陪着你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会有障碍要克服', 'There Will Be Obstacles To Overcome');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会特别顺利', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会被一直依赖的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会让你痛苦的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会让周围的人感受到温暖', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('似乎已经是真实的了', 'Act As Though It Is Already Real');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('但行好事，莫问前程', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('何以解忧，唯有暴富', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你一定有支持', 'You Are Sure To Have Support');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你不会失望的', 'You Will Not Be Disappointed');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你不得不妥协', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你不是真心在意', 'You Don''t Really Care');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你不用最棒', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你也许会失望', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会发现一切你需要知道的', 'You Will Find Out Everything You''ll Need To Know');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会后悔的', 'You''ll Regret It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会因为你做了的而感到快乐', 'You''be Happy You Did');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会因为做了而感到快乐', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会失望的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会失望的', 'You Will Not Be Disappointed');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会很高兴你做了', 'You''ll Be Happy You Did');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会得到最后想要的结局', 'You''ll Get The Final Word');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会得到最后的决定', 'You''ll Get The Final Word');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你会忘记它', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你做什么都没用', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你只是有点寂寞', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能不得不放弃其他东西', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能不得不放弃其他东西', 'You May Have To Drop Other Things');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能会反对', 'You May Have Opposition');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能会发现你自己无法妥协', 'You Could Find Yourself Unable To Compromise');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能会失去一些东西', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能会放弃其他的东西', 'You May Have To Drop Other Things');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能会比较悲伤', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能觉得自己无法妥协', 'You Could Find Yourself Unable To Compromise');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你可能需要放下其他东西', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你在开玩笑吗', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你在开玩笑吗？', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你大概会受点伤', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你太近的看了', 'You Are Too Close To See');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你失去的某天会以不同的方式归还于你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你好像舍不得', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将不得不妥协', 'You''ll Have To Compromise');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将不得不补回来', 'You''ll Have To Make It Up As You Go');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将会发现你所想了解的一切', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将会发现你需要知道的一切', 'You Will Find Out Everything You''ll Need To Know');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将会后悔的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将会有好的运气', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将取得成功', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你将需要适应', 'You Will Need To Accommodate');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你就是答案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你开心就好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你当然可以失败', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你很幸运', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你很棒，自信起来吧！', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你心里已有答案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你心里已经有答案了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你必须', 'You Must');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你必须弥补这个缺点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你必须现在就行动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你必须现在行动', 'You Must Act Now');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你必须解决一些相关的问题', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你或许需要突破', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你无法掌控', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你无法继续沉睡', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你有必要傻一点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你猜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你现在必须行动', 'You Must Act Now');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你的状态很不对', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你的行为将会改善这件事', 'Your Actions Will Improve Things');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你的行动将会改善', 'Your Actions Will Improve Things');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你看的太近了', 'You Are Too Close To See');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你真的不在乎', 'You Don''t Really Care');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你知道现在比以前更好', 'You Know Better Now Than Ever Before');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你知道现在比任何时候都好', 'You Know Better Now Than Ever Before');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你祈求的一切顺利', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你肯定会被支持的', 'You Are Sure To Have Support');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你要勇敢的离开', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你认为是对的，就去做吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你说了算', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要一点帮助', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要主动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要主动出击', 'You''ll Need To Take The Initiative');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要掌握更多的信息', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要更多的信息', 'You''ll Need More Information');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要的只是勇气', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要知道真相', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要考虑其他办法', 'You''ll Need To Consider Other Ways');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要考虑其他方法', 'You''ll Need To Consider Other Ways');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要考虑其他方面', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要适应', 'You Will Need To Accommodate');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你需要采取主动', 'You''ll Need To Take The Initiative');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('你颜值不够，本书拒绝回答', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('使人警惕起来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保存', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保存你的实力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保存你的精力', 'Save Your Energy');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保密', 'Keep It To Yourselves');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保护你的温暖所在', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保持乐观', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保持你的好奇心，去挖掘真相', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保持头脑清醒', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保持开放的心态', 'Keep An Open Mind');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保持灵活', 'Remain Flexible');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('保持现状', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('信任', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('借助他人的经验', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('值得去做的事', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('值得喝一杯', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('值得奋斗', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('值得肯定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('倾听你内心的声音', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('做一个为什么的清单', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('做个了断', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('做个了断吧', 'Press For Closure');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('做好，面对意外的准备', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('做最坏的打算', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('停止', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('停止emo', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('停止向前', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('停止悲伤', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('傻瓜才会这么想', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('僵持不下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('允许你选择先休息一下', 'Allow Yoursele To Rest First');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('充满未知的迷惑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('先做点别的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('先允许自己休息一下', 'Allow Yourself To Rest First');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('先完成一些其他的事情', 'Finish Something Else First');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('先让自己休息', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('光明的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('克制', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('克服困难', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('全力以赴', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('全部给它', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('关注你的家庭生活', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('关注生活本身', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('其他人将取决于你的选择', 'Others Will Depend On Your Choices');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('其实什么都没有', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('其实大家都知道', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('再也不要见', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('再多考虑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('再慷慨大方一点', 'Be More Generous');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('再等等看', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('再考虑一下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('再过几年', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('冒险一试', 'Take A Chance');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('决定了就去做', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('准备迎接意外', 'Prepare For The Unexpected');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('出发', 'Move On');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('出门遇贵人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('分久必合', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('分享是一种快乐', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('分清哪些是真正，对你重要的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('列个清单', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('列出原因', 'Make A List Of Why');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('删除你自己的障碍物', 'Remove Your Own Obstacles');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('删除记忆', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别不自量力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别人会对你苦笑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别傻了', 'Don''t Be Ridiculous');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别傻等了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别压抑自己的天性', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别太沉迷', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别太赶了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别忘了乐趣', 'Don''t Forget To Have Fun');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别忘了初心', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别忽视显而易见的', 'Don''t Ignore The Obvious');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别总想着过去了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别想了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别指望所有人理解你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别浪费你的时间', 'Don''t Waste Your Time');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别浪费时间了', 'Don''t Waste Your Time');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别灰心人生总是，起起落落落落的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别瞎折腾了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别要求太多', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别让它影响到你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别辜负了自己就好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别迷失自我', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别那么荒唐', 'Don''t Be Ridiculous');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别钻牛角尖了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别难过 你是最棒的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('别难过你是最棒的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('到此为止', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('制定计划', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('制订了一个新计划', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('努力向前就可以了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('努力就有收获', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('勿忘初心，放得始终', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('十分好的预感', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('千万不能失败', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('千万别信', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('千万别傻', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('协作', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('卑微的等待', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('原点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去争取机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去倾诉', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去做', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去做其他的事情', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去做吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去尝试', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去忘记', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去改变', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去欣然的肯定它', 'Be Delightfully Sure Of It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去爱', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去看更多风景', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去行动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去解决', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去遵循专家的建议', 'Follow The Advice Of Experts');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('去问你爸爸', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('又干净又明亮', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('发挥你的想象力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('取决于你的选择', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('取暖', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('另择吉日', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('只做一次', 'Only Do It Once');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('只是一场梦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('只有一次机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('只要你说“谢谢”', 'Provided You Say "Thank You"');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可以', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可以有', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可以期待的未来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可怕', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可能会发生结果令人吃惊的事情', 'Startling Events May Occur As A Result');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可能会很累', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可能会是陌生的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可能会让你，泪流满面的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可能会迟到，但绝不会缺席', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可能意味着失去', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('可能有另一种情况', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('吃得苦中苦，还是普通人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('吃点东西 冷静一下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('吃点东西冷静一下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('吃点东西，冷静一下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('合久必分', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('合作将会是关键', 'Collaboration Will Be The Key');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('同意', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('听听专家怎么说', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('听听专家的意见', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('听听别人怎么说', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('告别', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('告诉别人它对你意味着什么', 'Tell Someone What It Means To You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('告诉别人这对你的意义', 'Tell Someone What It Means To You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('告诉自己什么是最重要的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('呼吸一下新鲜空气', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('唤醒沉睡的你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('善待自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('喊不醒装睡的人的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('回到原点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('回头看看', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('回家', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('在这个时候不要问太多了', 'Don''t Ask For Any More At This Time');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('地点不合适', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('坑总在那里，不来不去', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('坚强', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('坚持', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('坚持了不该坚持的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('坚持才会有效果', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('坚毅沉着就会胜利', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('培养一项新的爱好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('堕落', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('复杂的事情简单做', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('多余', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('多回头看看', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('多读一本书', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大哭一场会好受些', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大哭一场会好受点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大声说出来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大家好像都不认同', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大方一点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大概可能也许', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大概吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大概要多想一会儿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大胆一点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('大量的事需要努力', 'A Substantial Effort Will Be Required');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('天上要掉馅饼了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('太糟糕了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('失去又不会死掉', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('失去的会以不同的方式归还于你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('奇迹', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('奇迹即将降临', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('好像会很累', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('好像会有很大的麻烦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('好像平凡了点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('好天气', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('好的坏的都是风景', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('好的指引', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('好运将会降临', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('如你所愿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('如果你不反抗', 'If You Don''t Resist');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('如果你不孤单', 'Not If You''re Alone');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('如果你不抗拒', 'If You Don''t Resist');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('如果你按你说的做', 'If You Do As You''re Told');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('妥协', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('存在即合理', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('孤单', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会好奇', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会妥协', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会改变什么', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会放弃', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会爱人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会珍惜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会自我治愈', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会表达自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会认错', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('学会释然', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它不可能失败', 'It Cannot Fall');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它仍将无法预测', 'It Will Remain Unpredictable');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它会带来好运', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它会影响到别人对你的看法', 'It Will Affect How Others See You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它会支持你的', 'It Will Sustain You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它会让你付出代价', 'It''ll Cost You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它可能已经处理完了', 'It May Already Be A Done Deal');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它可能是非凡的', 'It Could Be Extraordinary');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它将会浪费金钱', 'That Would Be A Waste Of Money');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它将使你付出', 'It''ll Cost You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它将使你坚持下去', 'It Will Keep You Going');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它将使你撑下去', 'It Will Sustain You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它将带来好运', 'It Will Bring Good Luck');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('它肯定会让事情更有趣', 'It Is Sure To Make Things Interesting');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('守护', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('安静', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('完成其他事情的第一', 'Finish Something Else First');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('完美时刻', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('实际一点', 'Be Practical');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('实际一点吧', 'Be Practical');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('容易被操纵', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('对不起', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('对他人慷慨', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('对未知前途的期盼', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('对此感到怀疑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('对的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('对自己好一点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('对，去吧！', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('寻寻觅觅', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('寻找一个指路人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('寻找更多的选择', 'Seek Out More Options');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('寻找机会就行', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('将要奔赴一场未知的路程', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('将要被击溃', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尊重规则', 'Respect The Rules');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('小心谨慎的靠近', 'Approach Cautiously');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('小迷糊', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尚待时日', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尚未成功，仍需努力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尝试一下', 'Take A Chance');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尝试一种不太可能的解决方案', 'Try A More Unlikely Solution');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('就差一点点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尽人事，听天命', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尽你最大的能力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尽在掌握之中', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尽情体验', 'Enjoy The Experience');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尽早去做', 'Do It Early');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尽早完成', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('尽早解决它', 'Settle It Soon');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('居心叵测', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('履行你的义务', 'Follow Through On Your Obligations');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('履行你自己的义务', 'Follow Through On Your Obligations');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('左边', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('差不多得了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('希望去解决', 'Expect To Settle');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('带着你顽皮的好奇心去探索它', 'Explore It With Playful Curiosity');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('常常是最后一把钥匙打开了神殿门', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('平凡之路', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('平分秋色', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('平平安安', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('平衡', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('并不会让你高兴', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('并不明智', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('并不确定真伪', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('并非永恒', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('幼稚又可笑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('开心的肯定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('当上帝给你关上门，会顺便关上窗', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('当局者迷', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('当然', 'Definitely');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('当然', 'Of Course');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('当然咯', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('形势不明', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('形同陌路', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('彼岸', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('很可能已成事实', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('很多事会随着，时间好起来的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('很快就会解决它', 'Settle It Soon');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('很快就能解决', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('很高兴做了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('很麻烦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('得不到别人的认同', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('得不到的，永远在骚动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('得到了多数的支持', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('得真正地努力一下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('心会冷掉', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('心存善念', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('必不可少', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('必须努力奔跑起来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('忘掉它', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('忽略了一件显而易见的事', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('怀念不如向前', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('怀疑', 'Doubt It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('怀疑它', 'Doubt It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('总会慢慢淡去的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('悄悄躲开', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('您需要了解更多信息', 'You''ll Need More Information');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('情况不明', 'The Situation Is Unclear');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('情况不清晰', 'The Situation Is Unclear');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('情况将很快发生改变', 'The Circumstances Will Change Very Quickly');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('情况很快会有改变', 'The Circumstances Will Change Very Quickly');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('情况很快就会发生变化', 'The Circumstances Will Change Very Quickly');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('情况很快就会发生改变', 'The Circumstances Will Change Very Quickly');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('想得美', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('想念', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('想想有没有机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('想法太多，选择太少', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('意义非凡', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('感恩，会越来越好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('愿意并且相信', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('慢下来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('慢些，我们就会更快', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('慢慢人生路，谁不错几步', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('慢慢来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('成为了事实', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('成长', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('我确定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('戒掉过分的急躁', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('或许，当你长大', 'Perhaps, When You''re Older');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('所有事都会慢慢好起来的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('才刚刚开始', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('打赌', 'Bet On It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('扔掉这些东西', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('扫除障碍', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('找个人给你意见', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('找回自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('把它写下来', 'Get It In Writing');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('把心揣怀里', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('把握现在', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('把重心放在工作/学习上', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('把问题交给投硬币', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('抓住机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('抗拒', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('抛弃首选方案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('拜拜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('拭目以待', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('拼凑不了的昨天', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('按下关闭', 'Press For Closure');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('按照一定的规律到达了终点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('按照你的意愿', 'Follow Through With Your Good Intentions');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('挥别错的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('挥手道别', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('挽留', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('捍卫它', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('捕风捉影', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('换一个方向', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('换个角度想想', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('掌握更多信息', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('排好手头事情，的优先级', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('探讨其俏皮的好奇心', 'Explore It With Playful Curiosity');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('接受改变你的日常行为', 'Accept A Change To Your Routine');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('接受的终将会接受', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('接受那些消失的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('控制自己的情绪', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('援助会让你成功进步', 'Assistance Would Make Your Progress A Success');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('改变不了世界，改变自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('改变心情', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('改变自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放下手机', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放在心里吧这样比较好点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放弃第一个方案', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放心，会有人陪着你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放手', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放松步伐去继续进行更多', 'Proceed At A More Relaxed Pace');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放轻松点，慢慢来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('放轻松，这很简单', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('数到10；再问一遍', 'Count To 10; Ask Again');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('敲吧，门终究会开的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('断舍离', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无条件的付出', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无法预测', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无解', 'No solution');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无论你做什么结果都是持久的', 'Whatever You Do The Results Will Be Lasting');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无论你做何种选择，结果都是对的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无论如何', 'No Matter What');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无论如何你可以提升', 'Upgrade Any Way You Can');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无谓的徘徊', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('无需担忧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('既然认准这条路，就不要去想走多久', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('旧梦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('时机不对', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('时机尚不成熟', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('时机未到', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('时间会告诉你一切', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('时间会证明一切', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('时间是最好的回答', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('时间有限', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('明天就会有新鲜事儿发生', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('明天就会有，新鲜事发生', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('明日曙光将四起', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('是', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('是你走的时候', 'It''s Time For You To Go');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('是值得的麻烦', 'It Is Worth The Trouble');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('是的', 'Yes');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('是的，但不要强迫', 'Yes,But Don''t Force It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('显得有些唐突', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('显而易见', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('晚些再处理它', 'Deal With It Later');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('暂且不要判断', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('更慷慨', 'Be More Generous');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最佳方案不一定可行', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最划算的交换', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最后一次机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最后什么都没改变', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最好专注于你的工作', 'It Would Be Better To Focus On Your Work');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最好的事情正要发生', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最好的解决办法可能不是明显的', 'The Best Solution May Not Be The Obvious One');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最好等一等', 'Better To Wait');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最特别的幸运', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最美丽的一天', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('最重要的东西，是眼睛看不到的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有一些重要的事', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有些人开始慌乱', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有些人选择了离开', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有些话不说，对大家都好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有人撑着你向前', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有人浪费了你的时间', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有人爱着你', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有充分的理由保持乐观', 'There Is Good Reason To Be Optimistic');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有可能', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有可能会发生意外', 'Mishaps Are Highly Probable');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有好运', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有意料之外的事会发生，不妨等待', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有时候选择太多，就代表着无从选择', 'Realize That Too Many Choices Is As Difficult As Too Few');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有比这更重要的东西', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有点儿心疼', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有点儿意思', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('有点唐突', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('期待常会落空', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('木已成舟', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('未来会变得特别繁忙', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('未来会变得，特别繁忙', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('未解之谜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('本来无一物，何处惹尘埃', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('本能', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('朴素', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('机不可失，失不再来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('机会不会很快再来', 'The Chance Will Not Come Again Soon');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('机会就在眼前', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('机会稍纵即逝', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('条条大路通罗马', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('果断点离开', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('欢天喜地', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('欲戴王冠，需承其重', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('欲速则不达', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('殊途同归', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('残留的遗憾', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('毋庸置疑', 'Don''t Doubt It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('毫无疑问', 'Unquestionably');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('毫无道理', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('永恒', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('永远不会愈合的伤口', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('江湖险恶，不行就撤', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('沉默是金', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没事，有我在', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没人可以保证', 'There Is No Guarantee');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没什么好结果', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没什么放不下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没有', 'No');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没有什么是对的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没有保证', 'There Is No Guarantee');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没有更好的选择', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没法保证', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('没错', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('泡沫', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('注意一下周围', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('注意你的节奏', 'Watch Your Step As You Go');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('注意细节', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('注意身后', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('注重细节', 'Pay Attention To The Details');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('活下去', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('浪费光阴', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('消除你的障碍', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('消除你自己的障碍', 'Remove Your Own Obstacles');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('温柔的坚持就是胜利', 'Gentle Persistence Will Pay Off');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('漂亮', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('烦恼快要消失了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('照你想的那样去做', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('照你说的去做', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('爱', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('物是人非', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('特别的见解', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('犹豫是必经的过程', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('独角戏', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('玩得开心就好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('现在不是最好时机', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('现在不要再问更多了', 'Don''t Ask For Any More At This Time');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('现在就可以', 'Now You Can');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('现在比以往任何时候的情况都要好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('现在说不清', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('现在还说不清', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('现实很骨感', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('珍惜身边人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('甜蜜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('用一个更清晰的看法', 'Get A Clearer View');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('用任何你可以做到的方式提升', 'Upgrade Any Way You Can');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('用力活着', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('用尽一切办法去努力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('用平淡的心态去追求', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('用平淡的心态，去追求', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('留意左边', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('留意身边的人和事', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('白日梦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('白日梦?', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('盛开', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('目前不好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('直面残酷', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('相信你最初的想法', 'Trust Your Original Thought');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('相信你的直觉', 'Trust Your Intuition');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('相关的问题可能的浮出水面', 'Related Issues May Surface');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('相见不如怀念', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('相遇', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('省点力气吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('把它当作一个机会', 'Consider It An Opportunity');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('看向未来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('看看会发生什么', 'Watch And See What Happens');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('看缘分吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('看脸', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('看见的都不是真的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('看过海就不会在意池塘的是非对错', 'If you have seen the sea, you will not care about the right and wrong of the pond');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('眼光长远一点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('着眼未来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('睡一觉再问', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('研究它，然后享受它', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('确保一切顺利', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('禁言', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('抛弃旧的解决方案', 'Leave Behind Old Solutions');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('空想', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('空想家', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('突如其来的幸福', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('立一个小目标', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('站在了最重要的地方', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('站起来去战斗', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('笑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('笑着活下去', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('第二次被伤害的机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等一等', 'Wait');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等你再年长几岁，可能会…', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等待', 'Wait');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等待一下，更好的出价', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等待一个更好的机会', 'Wait For A Better Offer');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等待下一个故事的发生', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等待更好的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等待机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('等等', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('答案可能会在另一种语言', 'The Answer May Come To You In Another Language');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('答案在镜子里', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('答案就在你的“后院”', 'The Answer Is In Your Backyard');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('答案就在你身边', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('答案或许在你身边', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('算了吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('管它呢', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('糖吃多了会傻，苦一点没关系', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('终点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('结束倒计时', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('结果不错', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('结果会是好的', 'The Outcome Will Be Positive');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('结果会让你惊喜', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('结果可能让人惊讶', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('给人依赖', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('全力以赴', 'Give It All You''ve Got');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('给自己一个肯定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('绝不', 'Never');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('绝对不', 'Absolutely Not');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('绝对不是', 'Absolutely Not');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('绝对不要', 'Absolutely Not');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('绝对的', 'Absolutely');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('继续前行', 'Move On');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('继续前进', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('考虑一下这个机会', 'Consider It An Opportunity');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这很重要', 'It Is Significant');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('具有重大意义', 'It Is Significant');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('耐心点', 'Be Patient');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('耐心的等待', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('肯定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('肯定的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('背不动的就放下', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('背叛', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('背道而驰', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('胜券在握', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('能做的只有，把握现在', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('能呼吸上空气，就是幸运的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('能让你快乐的那个决定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('自信起来吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('自己选择的路，跪着也要走完', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('至关重要', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('节省你的精力', 'Save Your Energy');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('花多点时间去决定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('花更多的时间来决定', 'Take More Time To Decide');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('苦涩', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('苦的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('荒谬', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('获得更清晰的视野', 'Get A Clearer View');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('萌芽', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('藏在心里别说出来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('虚无的关系', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('虚空', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('表示怀疑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('被人肯定', 'Be Delightfully Sure Of It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('被唾弃的决定', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('被排挤', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要主动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要像UP一样学会等待', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要变通', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('选择太多和选择太少一样困难', 'Realize That Too Many Choices Is AS Difficult As Too Few');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要抓住问题的关键', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要有点耐心', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要有耐心', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要求不要太高', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要相信你很棒棒', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要知足', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要禁得起诱惑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要耐心', 'Be Patient');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('要解决', 'Expect To Settle');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('见好就收', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('观察形势', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('观望', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('认清现实吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('认清现实，再行动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('认真起来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('让你泪流满脸的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('让它过去吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('让自己开心一点', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('记录下来', 'Get It In Writing');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('讲述问题的表面', 'Related Issues May Surface');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('设定优先级是必要的', 'Setting Priorities Will Be A Necessary Part Of The Process');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试下改变', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试着去爱', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试着安静一会儿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试着慷慨一点儿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试着改变你的日常生活', 'Accept A Change To Your Routine');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试着更快一些', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试着面对自己真实的想法', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试着面对自己，真实的想法', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('试试卖萌', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('询问你的母亲', 'Ask Your Mother');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('询问你的父亲', 'Ask Your Father');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('该来的总会来', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('说出来吧', 'Speak Up About It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('请多点耐心', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('请教你的妈妈', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('谁说得准呢，先观望着', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('谁都不能保证', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('调查研究，然后享受它', 'Investigate And Then Enjoy It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('谢谢', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('谨慎小心', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('谨慎的接近', 'Approach Cautiously');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('负责', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('负责', 'Take Charge');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('走容易走的路', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('走心就好', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('走，回家吃顿饭吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('越困难越值得', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('越过山丘，无人等候', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('跟UP被白嫖视频一样', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('跟着感觉走', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('跟随你的意愿', 'Follow Through With Your Good Intentions');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('跟随其他人的领导', 'Follow Someone Else''s Lead');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('路见不平，绕道而行', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('踽踽独行', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('车到山前必有路', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('转个身忘记吧', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('转移你的注意力', 'Shift Your Focus');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('轮回', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('轻而易举的伤害', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('过去的事就让它过去吧', 'Let It Go');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('运用你的想象力', 'Use Your Imagination');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('还有别的选择', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('还有另一种情况', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不值得争取', 'It''s Not Worth A Struggle');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不值得努力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不切实际', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不可取', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不可能失败', 'It Cannot Fail');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不是你想要的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不是能犹豫的事儿', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这不是重要的', 'It Is Not Significant');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这个大概会让你哭泣', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这事儿不靠谱', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这事情要靠缘分', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这仍然是不可预测的', 'It Will Remain Unpredictable');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这件事会很麻烦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这件事你说了不算', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这会带来好运', 'It Will Bring Good Luck');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这会影响你的形象', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这会是件有趣的事情', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这似乎是确定无疑的', 'It Seems Assured');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这取决于你的行动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这可能已经是木已成舟', 'It May Already Be A Done Deal');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这可能很难，但你会发现它的价值', 'It May Be Difficult But You Will Find Value In It');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这可能是特别的', 'It Could Be Extraordinary');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这大概会让你有点寂寞', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将会创造一个扰乱', 'It Will Create A Stir');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('会有挫折需要克服', 'There Will Be Obstacles To Overcome');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将影响别人看你', 'It Will Affect How Others See You');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将很美好', 'It''s Gonna Be Great');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将是一件有乐趣的事情', 'It Will Be A Pleasure');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将是一种享受', 'It Will Be A Pleasure');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将是一种，金钱的浪费', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将是不明智的', 'It Would Be In Advisable');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将更好地专注于自己的工作', 'It Would Be Better To Focus On Your Work');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这将造成轰动', 'It Will Create A Stir');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这就是命', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这就是结局', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这并不重要', 'It Is Not Significant');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这时候非常顺利', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是一个不错的时间安排', 'It''s A Good Time To Make Plans');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是一个制定新计划的好时机', 'This Is A Good Time To Make A New Plan');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是一个很好的时机，来制定新计划', 'This Is A Good Time To Make A New Plan');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是一个很好的时间来制定计划', 'It''s Good Time To Make Plans');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是一个机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是一定的', 'That is for sure');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是一次机会', 'This is a chance');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是不值得的斗争', 'It''s Not Worth A Struggle');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是不明智的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是不明智的', 'It Would Be Inadvisable');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是不确定的', 'It Is Uncertain');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是个麻烦', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是件你忘不掉的事', 'It Is Something You Won''t Forget');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是你不会忘记的', 'It Is Something You Won''t Forget');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是你不会忘记的事情', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是你最后的机会', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是困难的，但你会发现它的价值', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是在浪费金钱', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是必然的，不要抗拒', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是昂贵的礼物', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是机智的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是毫无疑问的', 'It Is Certain');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是肯定的', 'It Is Certain');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是起跑线', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是非常重要', 'It Is Significant');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这有一个重要的东西用来过渡到另一个局面', 'There Is A Substantial Link To Another Situation');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这没什么意义', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这点麻烦是值得的', 'It Is Worth The Trouble');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这真是一个奇怪的问题', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这种事情不要告诉别人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这简直太有趣了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这绝对是个好主意', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这肯定会让事情变得有趣', 'It Is Sure To Make Things Interesting');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这辈子都不可能', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这难以置信', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('远行', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('迷人的危险', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('迷失的世界', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('退一步海阔天空', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('退后一厘米', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('逆水行舟', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('遇上方知有', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('遵守规则', 'Respect The Rules');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('遵循专家的建议', 'Follow The Advice Of Experts');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('遵循别人的引导', 'Follow Someone Else''s Lead');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('遵循智者的建议', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('避免第一个解决方案', 'Avoid The First Solution');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('那又怎样，那就这样', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('那将是浪费钱', 'That Would Be A Waste Of Money');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('这是你无法控制的', 'That''s Out Of Your Control');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('那超出你的能力范围', 'That''s Beyond Your Ability');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('醒醒吧，别做梦了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('采取冒险的态度', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('采取行动', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('采用冒险的态度', 'Adopt An Adventurous Attitude');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重新确定重要事项的优先级', 'Reprioritize What Is Important');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重新想想', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重新确定优先次序什么是重要的', 'Reprioritize What Is Important');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重新考虑', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重新考虑你的想法', 'Reconsider Your Thoughts');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重新考虑你的方法', 'Reconsider Your Approach');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重生', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重要', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('重逢', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('量力而行', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('错的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('问天问大地，不如问自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('问自己什么是最重要的', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('问问你最好的朋友', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('问问你的亲人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('问问自己，为什么要这么干', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('阻止', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('陌生人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('随TA去', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('随心而行', 'Let It Go');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('随波逐流未必是好事', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('随缘', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('隐忍', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('障碍重重', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('难分好坏', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('集中注意在细节上', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需找更多的选择', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要一个相当大的努力', 'A Substantial Effort Will Be Required');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要一腔孤勇', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要冒险', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要加速些', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要合作', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要大量的努力', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要总结规律', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('需要花费点时间', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('静观其变', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('非常融洽', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('面具戴久了，会变成另一个人', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('顺其自然', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('须以较宽松的步伐', 'Proceed At A More Relaxed Pace');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('驻足静立', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('驾驭', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('驾驭不了', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('骗不到自己', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('高兴起来吧你这么厉害', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('默数十秒再问我', '');
INSERT INTO `answer` (`chinese`, `english`) VALUES ('默默无闻', '');